### ISSUE TITLE
SAT file testing

### ISSUE THREAD

**Issue by easyw** [jmplonka/InventorLoader#11]
Hi, 
I'm trying to load this SAT test file
http://paulbourke.net/dataformats/sat/dice.sat
(here a doc on SAT format you may already have 
http://paulbourke.net/dataformats/sat/sat.pdf )
but the result is wrong:
![dice](https://user-images.githubusercontent.com/3032347/39044297-11eb1886-4490-11e8-8d2c-b81506618b03.png)

PS it would be possible to add to the 'FreeCAD\Mod\InventorLoader\Demo-Status' some SAT testing files as it is done for IPT?

Thx a lot for this WB!
Maurice

**Comment by jmplonka** [comment]
Hello Maurice.

Sorry for answering so late.

Meanwhile I added the option to convert IPT/SAT files to STEP format - this leads to the correct result.

The bug is caused by a simple problem: if you cut a sphere along an edge you get two surfaces. But, which one should I use?

Thank you very much for the hint to add SAT files to the Demo-Status folder.

Kind regards,
Jens
